pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging"'
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploying"'
        }
      }
    }
    stage('Clean up') {
      steps {
        script {
          sh 'echo "Staging"'
        }
      }
    }
    }
}