<<<<<<< HEAD
  # - name: import common file
  #   import_playbook: ../static-assignments/common.yml
  #   tags:
  #     - always

  # - name: env-vars file
  #   import_playbook: ../dynamic-assignments/env-vars.yml
  #   tags:
  #     - always

  # - name: import database file
  #   import_playbook: ../static-assignments/db.yml

  - name: import webservers file
    import_playbook: ../static-assignments/uat-webservers.yml

  # - name: Loadbalancers assignment
  # - import_playbook: ../static-assignments/loadbalancers.yml
  #   when: load_balancer_is_required
=======
---
 - hosts: db
 - name: database assignment
   ansible.builtin.import_playbook: ../static-assignments/database.yml

 - hosts: nginx
 - name: nginx assignment
   ansible.builtin.import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
# - name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

#- hosts: sonar
#- name: sonar assignment
#  ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml
>>>>>>> feature/jenkinspipeline-stages
